### ISSUE TITLE
Feaure request: dark color scheme

### ISSUE THREAD

**Issue by Mikaela** [macdonst/detect-missing-adblocker#1]
I have imported the element through unpkg on [Aminda.eu](https://aminda.eu) and it seems to be mostly immune to

```css
:root {
  color-scheme: dark light;
}
```

Regardless of whether I attempt to include it in my css (ignoring the custom css), in-line for the `<detect-missing-adblocker>` element or change the order which css is imported in.

The only thing that changes is the link colours, which again isn't too readable against the light background colour.

Otherwise I have workarounded this by forcing light colours for legibility, while preferably I would have the banner dark.

```css
.ftf-dma-note {
  color-scheme: only light;
}
```

I love the script otherwise, thank you.

**Comment by Mikaela** [comment]
Sorry about the noise, this turned out to be an user error.

First I was missing the `!important` and then `revert` causes transparency so the solution I ended up to was:

```scss
// Adblocker detection for dark themes
@media (prefers-color-scheme: dark) {
  .ftf-dma-note {
    color-scheme: only dark !important;
    color: #ffb700 !important;
    background-color: #000000 !important;
  }
}

// Adblocker detection for light themes
@media (prefers-color-scheme: light) {
  .ftf-dma-note {
    color-scheme: only light !important;
    color: #000000 !important;
    background-color: #ffffff !important;
  }
}
```
